# Generated by Django 4.2.7 on 2023-11-09 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processo', '0002_alter_processoadm_valor_atributo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='andamentoadm',
            name='valor_pago',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
