# Generated by Django 4.2.7 on 2023-11-09 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processo', '0004_alter_andamentoadm_valor_pago_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processoadm',
            name='valor_atributo',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=20, null=True),
        ),
    ]
