# Generated by Django 4.2.7 on 2023-11-09 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processo', '0005_alter_processoadm_valor_atributo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processoadm',
            name='valor_atributo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
