# Generated by Django 4.2.7 on 2023-11-09 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processo', '0006_alter_processoadm_valor_atributo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processoadm',
            name='cep',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='processoadm',
            name='valor_atributo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='processoadm',
            name='valor_atualizado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='processoadm',
            name='valor_credito',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='processoadm',
            name='valor_multa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True),
        ),
    ]
