# Generated by Django 4.2.7 on 2023-11-09 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processo', '0007_alter_processoadm_cep_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='andamentoadm',
            name='valor_pago',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True),
        ),
    ]
