# Generated by Django 4.2.7 on 2023-11-09 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processo', '0008_alter_andamentoadm_valor_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditoria',
            name='campos_alterados',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
