# Generated by Django 4.2.7 on 2023-11-09 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processo', '0009_alter_auditoria_campos_alterados'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditoria',
            name='campos_alterados',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
